#!/bin/bash
export VER=005pre3
#export CSS="$(cat ./css/style.css)"
#export CSS="$(cat ./css/{mobile,desktop}.css)"
#export CSS="$(cat ./css/tachyons-custom.css)"
export TACHYON_CSS="./css/tachyons-custom.css"
export STYLE_CSS="./css/style.css"
build-page(){
  (cat header.html
  cat $TACHYON_CSS
  cat body.html
  cat nav.html
  cat content.html 
  cat footer.html) | envsubst > "$VER.html"
}
build-page
