#!/usr/bin/env python3
filepath = 'clean.txt'
import re
with open(filepath) as fp:
    line = fp.readline()
    index=[]; # list of locations with keys: cnt, type and line
    cnt = 1
    while line:
        line=line.strip()
        if re.search(r'C.+: ',line) is not None:
            index.append({"cnt":cnt,"type":"chapterStart","line":line})
        if re.search(r'P.+: ',line) is not None:
            index.append({"cnt":cnt,"type":"promptStart","line":line})
        line = fp.readline()
        cnt += 1

#print("\n".join( map(lambda x: str(x).strip()[:79], index))) 
#print("\n".join( map(lambda x: str(x['cnt']), index))) 
for x in index:
  print(f'{x["cnt"]} {x["type"]} {x["line"][:55]}');
