#!/usr/bin/env python3
from enum import Enum

class State(Enum):
   IDLE=1
   IN_CHAPTER=2
   IN_PROMPT=3

state=State.IDLE

filepath = 'clean.txt'
import re
with open(filepath) as fp:
    line = fp.readline()
    index=[]; # list of locations with keys: cnt, type and line
    cnt = 1
    chapter=0
    prompt=0
    while line:
        line=line.strip()
        if re.search(r'C[0-9]+: ',line) is not None:
            # found a chapter
            prompt=0
            chapter+= 1
            state=State.IN_CHAPTER
            index.append({"cnt":cnt,"type":"chapterStart","line":line})
        if re.search(r'P.+: ',line) is not None:
            # found prompt
            if state==State.IN_PROMPT:
                prompt += 1
            if state!=State.IN_PROMPT:
                prompt += 1
            state=State.IN_PROMPT
            index.append({"cnt":cnt,"type":"promptStart","line":line})


        line = fp.readline()
        cnt += 1
        if len(line) > 0:
            input("Hit any key") 
            print(f'{cnt}: Chapter:{chapter}, Prompt:{prompt}')
            print(f'state:{state}\nline:{line}')

    index.append({"cnt":cnt,"type":"documentEnd","line":line})

if __name__ == __main__:
  for x in index:
    print(f'{x["cnt"]} {x["type"]} {x["line"][:55]}');
